import os
from fpdf import FPDF
from datetime import datetime

class ChallanPDF(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_fill_color(231, 76, 60)  # Red header
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('Arial', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'TRAFFIC VIOLATION CHALLAN', 0, 1, 'C')
        
        self.set_font('Arial', '', 10)
        self.cell(0, -5, 'Government of India | AI Enforcement Grid', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-25)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AI Traffic System on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')
        self.set_y(-15)
        self.cell(0, 10, 'This is a computer-generated document and does not require a physical signature.', 0, 0, 'C')

def generate_challan_pdf(challan_data, output_path):
    """
    Generates a professional PDF challan.
    challan_data: dict with id, plate, violation, fine, date, location, owner_name, etc.
    """
    pdf = ChallanPDF()
    pdf.add_page()
    
    # --- Main Info Box ---
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 15, f'Challan ID: #CH-{challan_data.get("id", "0000")}', 0, 1)
    
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, 55, 200, 55)
    pdf.ln(5)
    
    # --- Owner & Vehicle Column ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(95, 10, 'REGISTRATION DETAILS', 0, 0)
    pdf.cell(95, 10, 'VIOLATION DETAILS', 0, 1)
    
    pdf.set_font('Arial', '', 11)
    # Row 1
    pdf.cell(40, 8, 'Owner Name:', 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(55, 8, str(challan_data.get('owner_name', 'N/A')), 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.cell(40, 8, 'Violation Type:', 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(55, 8, str(challan_data.get('violation', 'Unknown')), 0, 1)
    
    # Row 2
    pdf.set_font('Arial', '', 11)
    pdf.cell(40, 8, 'Vehicle No:', 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(55, 8, str(challan_data.get('plate', 'N/A')), 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.cell(40, 8, 'Date & Time:', 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(55, 8, str(challan_data.get('date', 'N/A')), 0, 1)
    
    # Row 3
    pdf.set_font('Arial', '', 11)
    pdf.cell(40, 8, 'Vehicle Type:', 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(55, 8, str(challan_data.get('vehicle', 'N/A')), 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.cell(40, 8, 'Location:', 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(55, 8, str(challan_data.get('location', 'Chennai')), 0, 1)

    pdf.ln(10)
    
    # --- Fine Summary ---
    pdf.set_fill_color(248, 249, 250)
    pdf.rect(10, 105, 190, 40, 'F')
    
    pdf.set_y(110)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '     FINANCIAL SUMMARY', 0, 1)
    
    pdf.set_font('Arial', '', 12)
    pdf.cell(95, 10, '     Base Penalty Amount:', 0, 0)
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(192, 57, 43)
    pdf.cell(95, 10, f'Rs. {challan_data.get("fine", 500):,.2f}', 0, 1, 'R')
    
    pdf.set_text_color(44, 62, 80)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 5, f'     Status: {challan_data.get("status", "Unpaid")}', 0, 1)
    
    pdf.ln(15)
    
    # --- Important Instructions ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'IMPORTANT INSTRUCTIONS:', 0, 1)
    pdf.set_font('Arial', '', 10)
    instructions = [
        "1. This challan is generated automatically based on high-definition camera evidence.",
        "2. Fines must be paid within 15 days of the generation date to avoid further legal action.",
        "3. You can pay this challan online at http://localhost:5000/pay using UPI, Card, or Net Banking.",
        "4. If you believe this challan was issued in error, you may file a dispute at the local traffic court.",
        "5. Failure to pay may lead to vehicle blacklisting or registration cancellation."
    ]
    for line in instructions:
        pdf.multi_cell(0, 7, line)

    # --- QR Code Placeholder (Visual) ---
    pdf.set_draw_color(0, 0, 0)
    pdf.rect(160, 160, 30, 30)
    pdf.set_font('Arial', '', 7)
    pdf.text(162, 193, 'SCAN TO PAY')

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
